
version: '3.1'

services:
    db:
        image: mysql:5.7
        container_name: balbi-demo-airflow
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: db_demo-airflow
        ports:
            - "3309:3306"
        logging:
            driver: "json-file"
            options:
                max-size: "5MB"
                max-file: "1"